# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  branches:
    master:
      - step:
          name: Deploy app
          deployment: Production
          script:
            - pipe: atlassian/ssh-run:0.2.3
              variables:
                SSH_USER: $USER
                SERVER: $SERVER
                PORT: 22000
                COMMAND: 'cd /home/developer/joyout-partner-web-app && git pull && npm install && npm run build'

